# Generated by Django 4.1.5 on 2023-01-06 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_account_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='account_balance',
            new_name='balance',
        ),
    ]
