# Generated by Django 4.1.5 on 2023-01-06 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_paymentrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='date_created',
            new_name='transaction_date',
        ),
    ]
